UPV_TOKEN_URL = ''
UPV_TOKEN_TIMEOUT = 0
UPV_TOKEN_HEADERS = {"": ""}
UPV_UUID = ''
UPV_TOKEN_TYPE = {"": "", "": UPV_UUID}
UPV_USER = ''
UPV_PSW = ''

UPV_INFO_URL = ''
UPV_INFO_DATE_PARAM = ''
UPV_INFO_DATE_FORMAT = '%d/%m/%Y'
UPV_INFO_CAMPUS_PARAM = ''
UPV_INFO_CAMPUS_DEFAULT = ''
UPV_INFO_BAR_PARAM = ''
UPV_INFO_BAR_DEFAULT = ''
UPV_INFO_TIMEOUT = 0
UPV_INFO_HEADER_AUTH = ''
